### ISSUE TITLE
package name doesn't match rest of project

### ISSUE THREAD

**Issue by markstos** [smurthas/flickr-js#5]
This is published on NPM as 'strava-js' but everything else seems to reference 'flickr-js'.

If the package is not really related to Strava, perhaps it should be unpublished.

**Comment by smurthas** [comment]
The package published there is actually the starva-js repo, but its package.json references this github page. As such, the issue is the with the strava-js repo, for which I've created [an issue](https://github.com/smurthas/strava-js/issues/1).
